batailleNavale : main.o mapGeneration.o boatCreation.o automaton.o
	gcc main.o mapGeneration.o boatCreation.o automaton.o -o batailleNavale

main.o : main.c
	gcc -c main.c

mapGeneration.o : mapGeneration.c
	gcc -c mapGeneration.c

boatCreation.o : boatCreation.c
	gcc -c boatCreation.c

automaton.o : automaton.c
	gcc -c automaton.c